/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_AVANZADA_H_RPCGEN
#define _CALCULADORA_AVANZADA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX 10

typedef struct {
	u_int nums_len;
	int *nums_val;
} nums;

struct vector_operands {
	nums op1;
	nums op2;
};
typedef struct vector_operands vector_operands;

#define CALCADVANPROG 0x20000002
#define CALCADVANVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define VECTORSUM 1
extern  nums * vectorsum_1(vector_operands *, CLIENT *);
extern  nums * vectorsum_1_svc(vector_operands *, struct svc_req *);
extern int calcadvanprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VECTORSUM 1
extern  nums * vectorsum_1();
extern  nums * vectorsum_1_svc();
extern int calcadvanprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nums (XDR *, nums*);
extern  bool_t xdr_vector_operands (XDR *, vector_operands*);

#else /* K&R C */
extern bool_t xdr_nums ();
extern bool_t xdr_vector_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_AVANZADA_H_RPCGEN */
