/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora_avanzada.h"

bool_t
xdr_v (XDR *xdrs, v *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v_val, (u_int *) &objp->v_len, MAX,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vector_operands (XDR *xdrs, vector_operands *objp)
{
	register int32_t *buf;

	 if (!xdr_v (xdrs, &objp->op1))
		 return FALSE;
	 if (!xdr_v (xdrs, &objp->op2))
		 return FALSE;
	return TRUE;
}
