/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora_avanzada.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

v *
vectorsum_1(vector_operands *argp, CLIENT *clnt)
{
	static v clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VECTORSUM,
		(xdrproc_t) xdr_vector_operands, (caddr_t) argp,
		(xdrproc_t) xdr_v, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
