/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX 10

typedef struct {
	u_int nums_len;
	int *nums_val;
} nums;

struct operands {
	int op1;
	int op2;
};
typedef struct operands operands;

#define CALCPROG 0x20000001
#define CALCSIMPLEVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  int * sum_1(nums *, CLIENT *);
extern  int * sum_1_svc(nums *, struct svc_req *);
#define SUB 2
extern  int * sub_1(operands *, CLIENT *);
extern  int * sub_1_svc(operands *, struct svc_req *);
#define MULT 3
extern  int * mult_1(nums *, CLIENT *);
extern  int * mult_1_svc(nums *, struct svc_req *);
#define DIV 4
extern  float * div_1(operands *, CLIENT *);
extern  float * div_1_svc(operands *, struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MULT 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nums (XDR *, nums*);
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_nums ();
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
